#!/usr/bin/env bash
echo "== list newest buckets"

aws s3api list-buckets --output json | jq -r '
  .Buckets | sort_by(.CreationDate) | reverse | .[:5] + (if length > 5 then [{"Name": "..."}] else [] end) | .[] | .Name'